# # This is script for https://cloud.google.com/cloud-build/
# steps:
# # Install
# - name: 'gcr.io/cloud-builders/npm'
#   args: ['install']
# # Build
# - name: 'gcr.io/cloud-builders/npm'
#   args: ['run', 'build']
#   env:
#   - 'REACT_APP_BACKEND_URL=${_REACT_APP_BACKEND_URL}'
#   - 'NODE_PATH=./src'
# # Deploy
# - name: gcr.io/cloud-builders/gsutil
#   args: ["-m", "rsync", "-d", "-r", "build", "gs://${_FE_STAGING_BUCKET_NAME}"]
# # Grant public permission
# # TODO: it should be remove, by setting default permissions for the bucket.
# - name: gcr.io/cloud-builders/gsutil
#   args: ["-m", "acl", "ch", "-u", "AllUsers:R", "gs://${_FE_STAGING_BUCKET_NAME}/**"]

# This is script for https://cloud.google.com/cloud-build/
steps:
# Step 0: FRONTEND npm install
- name: "gcr.io/cloud-builders/npm"
  dir: 'frontend'
  args: ['install']
  timeout: "5m"

# Step 1: FRONTEND optimized build
- name: "gcr.io/cloud-builders/npm"
  dir: 'frontend'
  args: ["run", "build"]
  timeout: "5m"

# Step 2: FRONTEND Deploy cloud app frontend
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy", "-v", "0-1-2", "app.yaml"]
  dir: 'frontend'
  timeout: "20m"

timeout: 60m